In [98]:
import pandas as pd

In [99]:
cust_data=pd.read_csv("IPBA Dataset - NEW IPBA_BYOP DATASET.csv")
cust_data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase \nAmount (USD),Location,Size,Color,Season,Review \nRating,Subscription \nStatus,Payment \nMethod,Shipping \nType,Discount \nApplied,Promo Code\n Used,Previous\n Purchases,Preferred Payment\n Method,Frequency of\n Purchases,Previous Purchased \nAmount (USD),Average \nOrder Value (USD),Total Sales \nRevenue Per Customer (USD),Time spend on website Minutes,clicks,total number of impressions,Click-through rate (CTR),Website Traffic,Conversion\n Rate %
0,1,55,Male,Blouse,Clothing,$53.00,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,$554.00,$40.47,$607.00,55,2,95,2.11%,61,3.28%
1,2,19,Male,Sweater,Clothing,$64.00,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,$122.00,$62.00,$186.00,31,2,230,0.87%,41,4.88%
2,3,50,Male,Jeans,Clothing,$73.00,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,$579.00,$27.17,$652.00,31,1,213,0.47%,106,0.94%
3,4,21,Male,Sandals,Footwear,$90.00,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,$600.00,$13.80,$690.00,16,0,173,0.00%,25,0.00%
4,5,45,Male,Blouse,Clothing,$49.00,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,$378.00,$13.34,$427.00,20,1,337,0.30%,13,7.69%

In [100]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)  

print(cust_data.head(50))

    Customer ID  Age Gender Item Purchased     Category  \
0             1   55   Male         Blouse     Clothing
1             2   19   Male        Sweater     Clothing
2             3   50   Male          Jeans     Clothing
3             4   21   Male        Sandals     Footwear
4             5   45   Male         Blouse     Clothing
5             6   46   Male       Sneakers     Footwear
6             7   63   Male          Shirt     Clothing
7             8   27   Male         Shorts     Clothing
8             9   26   Male           Coat    Outerwear
9            10   57   Male        Handbag  Accessories
10           11   53   Male          Shoes     Footwear
11           12   30   Male         Shorts     Clothing
12           13   61   Male           Coat    Outerwear
13           14   65   Male          Dress     Clothing
14           15   64   Male           Coat    Outerwear
15           16   64   Male          Skirt     Clothing
16           17   25   Male     Sunglasses  Accessories
17           18   53   Male          Dress     Clothing
18           19   52   Male        Sweater     Clothing
19           20   66   Male          Pants     Clothing
20           21   21   Male          Pants     Clothing
21           22   31   Male          Pants     Clothing
22           23   56   Male          Pants     Clothing
23           24   31   Male          Pants     Clothing
24           25   18   Male         Jacket    Outerwear
25           26   18   Male         Hoodie     Clothing
26           27   38   Male        Jewelry  Accessories
27           28   56   Male         Shorts     Clothing
28           29   54   Male        Handbag  Accessories
29           30   31   Male          Dress     Clothing
30           31   57   Male        Jewelry  Accessories
31           32   33   Male          Dress     Clothing
32           33   36   Male         Jacket    Outerwear
33           34   54   Male          Pants     Clothing
34           35   36   Male        T-shirt     Clothing
35           36   54   Male         Blouse     Clothing
36           37   35   Male        T-shirt     Clothing
37           38   35   Male          Jeans     Clothing
38           39   29   Male          Dress     Clothing
39           40   70   Male          Pants     Clothing
40           41   69   Male        Handbag  Accessories
41           42   67   Male          Scarf  Accessories
42           43   20   Male           Coat    Outerwear
43           44   25   Male          Scarf  Accessories
44           45   39   Male            Hat  Accessories
45           46   50   Male          Socks     Clothing
46           47   57   Male          Shirt     Clothing
47           48   55   Male        Jewelry  Accessories
48           49   42   Male          Shirt     Clothing
49           50   68   Male         Hoodie     Clothing

   Purchase \nAmount (USD)        Location Size      Color  Season  \
0                   $53.00        Kentucky    L       Gray  Winter
1                   $64.00           Maine    L     Maroon  Winter
2                   $73.00   Massachusetts    S     Maroon  Spring
3                   $90.00    Rhode Island    M     Maroon  Spring
4                   $49.00          Oregon    M  Turquoise  Spring
5                   $20.00         Wyoming    M      White  Summer
6                   $85.00         Montana    M       Gray    Fall
7                   $34.00       Louisiana    L   Charcoal  Winter
8                   $97.00   West Virginia    L     Silver  Summer
9                   $31.00        Missouri    M       Pink  Spring
10                  $34.00        Arkansas    L     Purple    Fall
11                  $68.00          Hawaii    S      Olive  Winter
12                  $72.00        Delaware    M       Gold  Winter
13                  $51.00   New Hampshire    M     Violet  Spring
14                  $53.00        New York    L       Teal  Winter
15                  $81.00    Rhode Island    M       Teal  Winter
16                  $36.00         Alabama    S       Gray  Spring
17                  $38.00     Mississippi   XL   Lavender  Winter
18                  $48.00         Montana    S      Black  Summer
19                  $90.00    Rhode Island    M      Green  Summer
20                  $51.00       Louisiana    M      Black  Winter
21                  $62.00  North Carolina    M   Charcoal  Winter
22                  $37.00      California    M      Peach  Summer
23                  $88.00        Oklahoma   XL      White  Winter
24                  $22.00         Florida    M      Green    Fall
25                  $25.00           Texas    M     Silver  Summer
26                  $20.00          Nevada    M        Red  Spring
27                  $56.00        Kentucky    L       Cyan  Summer
28                  $94.00  North Carolina    M       Gray    Fall
29                  $48.00         Wyoming    S      Black    Fall
30                  $31.00  North Carolina    L      Black  Winter
31                  $79.00   West Virginia    L      Brown  Winter
32                  $67.00          Kansas    M     Silver  Summer
33                  $38.00        Colorado    L      Green  Summer
34                  $91.00    North Dakota    L     Violet  Spring
35                  $33.00   Massachusetts    M       Cyan  Summer
36                  $69.00        Illinois    M     Maroon  Winter
37                  $45.00         Indiana    S       Cyan  Summer
38                  $37.00         Florida    M        Red  Winter
39                  $60.00         Arizona    S  Turquoise  Summer
40                  $76.00       Louisiana    L      Beige  Winter
41                  $39.00          Alaska    M     Orange  Spring
42                 $100.00       Tennessee    M      Beige  Spring
43                  $69.00            Ohio    L   Lavender    Fall
44                  $53.00        Kentucky    S     Silver  Summer
45                  $21.00       Tennessee   XL     Indigo    Fall
46                  $43.00      California    L      White  Summer
47                  $54.00         Montana    M   Charcoal  Winter
48                  $55.00          Nevada    M     Orange  Summer
49                  $30.00      New Jersey    S     Indigo  Spring

    Review \nRating Subscription \nStatus Payment \nMethod Shipping \nType  \
0               3.1                   Yes      Credit Card         Express
1               3.1                   Yes    Bank Transfer         Express
2               3.1                   Yes             Cash   Free Shipping
3               3.5                   Yes           PayPal    Next Day Air
4               2.7                   Yes             Cash   Free Shipping
5               2.9                   Yes            Venmo        Standard
6               3.2                   Yes       Debit Card   Free Shipping
7               3.2                   Yes       Debit Card   Free Shipping
8               2.6                   Yes            Venmo         Express
9               4.8                   Yes           PayPal  2-Day Shipping
10              4.1                   Yes      Credit Card    Store Pickup
11              4.9                   Yes           PayPal    Store Pickup
12              4.5                   Yes           PayPal         Express
13              4.7                   Yes       Debit Card         Express
14              4.7                   Yes           PayPal   Free Shipping
15              2.8                   Yes      Credit Card    Store Pickup
16              4.1                   Yes            Venmo    Next Day Air
17              4.7                   Yes       Debit Card  2-Day Shipping
18              4.6                   Yes    Bank Transfer   Free Shipping
19              3.3                   Yes            Venmo        Standard
20              2.8                   Yes      Credit Card         Express
21              4.1                   Yes      Credit Card    Store Pickup
22              3.2                   Yes             Cash    Store Pickup
23              4.4                   Yes      Credit Card         Express
24              2.9                   Yes             Cash    Store Pickup
25              3.6                   Yes    Bank Transfer         Express
26              3.6                   Yes             Cash    Next Day Air
27              5.0                   Yes       Debit Card    Next Day Air
28              4.4                   Yes       Debit Card   Free Shipping
29              4.1                   Yes            Venmo    Store Pickup
30              4.7                   Yes    Bank Transfer        Standard
31              4.7                   Yes            Venmo    Store Pickup
32              4.9                   Yes    Bank Transfer   Free Shipping
33              3.3                   Yes            Venmo    Store Pickup
34              4.6                   Yes       Debit Card  2-Day Shipping
35              4.0                   Yes    Bank Transfer  2-Day Shipping
36              4.6                   Yes             Cash   Free Shipping
37              2.8                   Yes       Debit Card    Store Pickup
38              3.7                   Yes       Debit Card  2-Day Shipping
39              4.2                   Yes    Bank Transfer         Express
40              4.6                   Yes           PayPal    Next Day Air
41              4.5                   Yes             Cash        Standard
42              4.1                   Yes    Bank Transfer   Free Shipping
43              3.7                   Yes           PayPal    Store Pickup
44              4.6                   Yes    Bank Transfer   Free Shipping
45              2.9                   Yes            Venmo  2-Day Shipping
46              2.9                   Yes            Venmo    Store Pickup
47              4.5                   Yes       Debit Card   Free Shipping
48              2.7                   Yes       Debit Card    Store Pickup
49              4.6                   Yes    Bank Transfer    Next Day Air

   Discount \nApplied Promo Code\n Used  Previous\n Purchases  \
0                 Yes               Yes                    14
1                 Yes               Yes                     2
2                 Yes               Yes                    23
3                 Yes               Yes                    49
4                 Yes               Yes                    31
5                 Yes               Yes                    14
6                 Yes               Yes                    49
7                 Yes               Yes                    19
8                 Yes               Yes                     8
9                 Yes               Yes                     4
10                Yes               Yes                    26
11                Yes               Yes                    10
12                Yes               Yes                    37
13                Yes               Yes                    31
14                Yes               Yes                    34
15                Yes               Yes                     8
16                Yes               Yes                    44
17                Yes               Yes                    36
18                Yes               Yes                    17
19                Yes               Yes                    46
20                Yes               Yes                    50
21                Yes               Yes                    22
22                Yes               Yes                    32
23                Yes               Yes                    40
24                Yes               Yes                    16
25                Yes               Yes                    14
26                Yes               Yes                    13
27                Yes               Yes                     7
28                Yes               Yes                    41
29                Yes               Yes                    14
30                Yes               Yes                    16
31                Yes               Yes                    45
32                Yes               Yes                    37
33                Yes               Yes                    45
34                Yes               Yes                    38
35                Yes               Yes                    48
36                Yes               Yes                    44
37                Yes               Yes                    10
38                Yes               Yes                    44
39                Yes               Yes                    18
40                Yes               Yes                    31
41                Yes               Yes                    40
42                Yes               Yes                    15
43                Yes               Yes                    19
44                Yes               Yes                    45
45                Yes               Yes                    25
46                Yes               Yes                    45
47                Yes               Yes                    36
48                Yes               Yes                    38
49                Yes               Yes                    34

   Preferred Payment\n Method Frequency of\n Purchases  \
0                       Venmo              Fortnightly
1                        Cash              Fortnightly
2                 Credit Card                   Weekly
3                      PayPal                   Weekly
4                      PayPal                 Annually
5                       Venmo                   Weekly
6                        Cash                Quarterly
7                 Credit Card                   Weekly
8                       Venmo                 Annually
9                        Cash                Quarterly
10              Bank Transfer                Bi-Weekly
11              Bank Transfer              Fortnightly
12                      Venmo              Fortnightly
13                     PayPal                   Weekly
14                 Debit Card                   Weekly
15                     PayPal                  Monthly
16                 Debit Card                Bi-Weekly
17                      Venmo                Quarterly
18                       Cash                   Weekly
19                 Debit Card                Bi-Weekly
20                       Cash           Every 3 Months
21                 Debit Card                Quarterly
22                 Debit Card                 Annually
23                Credit Card                   Weekly
24                 Debit Card                   Weekly
25                     PayPal                 Annually
26                Credit Card                 Annually
27              Bank Transfer           Every 3 Months
28                     PayPal           Every 3 Months
29                Credit Card                   Weekly
30                Credit Card                  Monthly
31                      Venmo                  Monthly
32                      Venmo                 Annually
33                       Cash                Quarterly
34                     PayPal                Quarterly
35                Credit Card                Bi-Weekly
36                     PayPal              Fortnightly
37                     PayPal                   Weekly
38                      Venmo           Every 3 Months
39                Credit Card                  Monthly
40                 Debit Card                Quarterly
41                      Venmo                 Annually
42                     PayPal                 Annually
43                     PayPal              Fortnightly
44                     PayPal                   Weekly
45                     PayPal                 Annually
46                       Cash                Quarterly
47                       Cash                   Weekly
48                       Cash                  Monthly
49                 Debit Card                Bi-Weekly

   Previous Purchased \nAmount (USD) Average \nOrder Value (USD)  \
0                            $554.00                      $40.47
1                            $122.00                      $62.00
2                            $579.00                      $27.17
3                            $600.00                      $13.80
4                            $378.00                      $13.34
5                            $280.00                      $20.00
6                            $300.00                       $7.70
7                            $412.00                      $22.30
8                            $582.00                      $75.44
9                            $244.00                      $55.00
10                           $405.00                      $16.26
11                           $588.00                      $59.64
12                           $418.00                      $12.89
13                           $352.00                      $12.59
14                           $156.00                       $5.97
15                           $408.00                      $54.33
16                           $204.00                       $5.33
17                            $73.00                       $3.00
18                            $54.00                       $5.67
19                            $71.00                       $3.43
20                           $115.00                       $3.25
21                           $278.00                      $14.78
22                           $197.00                       $7.09
23                            $56.00                       $3.51
24                           $523.00                      $32.06
25                           $177.00                      $13.47
26                           $307.00                      $23.36
27                           $383.00                      $54.88
28                           $106.00                       $4.76
29                           $314.00                      $24.13
30                           $266.00                      $17.47
31                            $15.00                       $2.04
32                           $419.00                      $12.79
33                            $22.00                       $1.30
34                           $516.00                      $15.56
35                           $336.00                       $7.53
36                           $584.00                      $14.51
37                           $214.00                      $23.55
38                           $165.00                       $4.49
39                           $487.00                      $28.79
40                           $585.00                      $20.66
41                           $142.00                       $4.41
42                           $182.00                      $17.63
43                           $583.00                      $32.60
44                           $389.00                       $9.61
45                           $577.00                      $23.00
46                           $419.00                      $10.04
47                           $470.00                      $14.16
48                           $353.00                      $10.46
49                           $139.00                       $4.83

   Total Sales \nRevenue Per Customer (USD)  Time spend on website  Minutes  \
0                                   $607.00                              55
1                                   $186.00                              31
2                                   $652.00                              31
3                                   $690.00                              16
4                                   $427.00                              20
5                                   $300.00                              21

In [101]:
cust_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 28 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Customer ID                              3900 non-null   int64
 1   Age                                      3900 non-null   int64
 2   Gender                                   3900 non-null   object
 3   Item Purchased                           3900 non-null   object
 4   Category                                 3900 non-null   object
 5   Purchase
Amount (USD)                   3900 non-null   object
 6   Location                                 3900 non-null   object
 7   Size                                     3900 non-null   object
 8   Color                                    3900 non-null   object
 9   Season                                   3900 non-null   object
 10  Review
Rating                           3900 non-null   float64
 11  Subscription
Status                     3900 non-null   object
 12  Payment
Method                          3900 non-null   object
 13  Shipping
Type                           3900 non-null   object
 14  Discount
Applied                        3900 non-null   object
 15  Promo Code
 Used                         3900 non-null   object
 16  Previous
 Purchases                      3900 non-null   int64
 17  Preferred Payment
 Method                3900 non-null   object
 18  Frequency of
 Purchases                  3900 non-null   object
 19  Previous Purchased
Amount (USD)         3900 non-null   object
 20  Average
Order Value (USD)               3900 non-null   object
 21  Total Sales
Revenue Per Customer (USD)  3900 non-null   object
 22  Time spend on website  Minutes           3900 non-null   int64
 23   clicks                                  3900 non-null   int64
 24  total number of impressions              3900 non-null   int64
 25  Click-through rate (CTR)                 3900 non-null   object
 26  Website Traffic                          3900 non-null   int64
 27  Conversion
 Rate %                       3900 non-null   object
dtypes: float64(1), int64(7), object(20)
memory usage: 853.3+ KB

In [102]:
cust_data.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase \nAmount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review \nRating', 'Subscription \nStatus', 'Payment \nMethod',
       'Shipping \nType', 'Discount \nApplied', 'Promo Code\n Used',
       'Previous\n Purchases', 'Preferred Payment\n Method',
       'Frequency of\n Purchases', 'Previous Purchased \nAmount (USD)',
       'Average \nOrder Value (USD)',
       'Total Sales \nRevenue Per Customer (USD)',
       'Time spend on website  Minutes', ' clicks ',
       'total number of impressions', 'Click-through rate (CTR)',
       'Website Traffic', 'Conversion\n Rate %'],
      dtype='object')

In [103]:
cust_data.isnull().sum()

Customer ID                                 0
Age                                         0
Gender                                      0
Item Purchased                              0
Category                                    0
Purchase \nAmount (USD)                     0
Location                                    0
Size                                        0
Color                                       0
Season                                      0
Review \nRating                             0
Subscription \nStatus                       0
Payment \nMethod                            0
Shipping \nType                             0
Discount \nApplied                          0
Promo Code\n Used                           0
Previous\n Purchases                        0
Preferred Payment\n Method                  0
Frequency of\n Purchases                    0
Previous Purchased \nAmount (USD)           0
Average \nOrder Value (USD)                 0
Total Sales \nRevenue Per Customer (USD)    0
Time spend on website  Minutes              0
 clicks                                     0
total number of impressions                 0
Click-through rate (CTR)                    0
Website Traffic                             0
Conversion\n Rate %                         0
dtype: int64

dropping the irrelevant columns

In [104]:
columns_to_drop=["Preferred Payment\n Method"]
cust_data.drop(columns=columns_to_drop, inplace=True)
cust_data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase \nAmount (USD),Location,Size,Color,Season,Review \nRating,Subscription \nStatus,Payment \nMethod,Shipping \nType,Discount \nApplied,Promo Code\n Used,Previous\n Purchases,Frequency of\n Purchases,Previous Purchased \nAmount (USD),Average \nOrder Value (USD),Total Sales \nRevenue Per Customer (USD),Time spend on website Minutes,clicks,total number of impressions,Click-through rate (CTR),Website Traffic,Conversion\n Rate %
0,1,55,Male,Blouse,Clothing,$53.00,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Fortnightly,$554.00,$40.47,$607.00,55,2,95,2.11%,61,3.28%
1,2,19,Male,Sweater,Clothing,$64.00,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Fortnightly,$122.00,$62.00,$186.00,31,2,230,0.87%,41,4.88%
2,3,50,Male,Jeans,Clothing,$73.00,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Weekly,$579.00,$27.17,$652.00,31,1,213,0.47%,106,0.94%
3,4,21,Male,Sandals,Footwear,$90.00,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,Weekly,$600.00,$13.80,$690.00,16,0,173,0.00%,25,0.00%
4,5,45,Male,Blouse,Clothing,$49.00,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,Annually,$378.00,$13.34,$427.00,20,1,337,0.30%,13,7.69%

Renaming the columns

In [105]:
cust_data.rename(columns={
    'Purchase \nAmount (USD)': 'Purchase Amount',
    'Review \nRating' : 'Rating',
    'Subscription \nStatus': 'Subscription',
    'Payment \nMethod' : 'Payment Method',
    'Shipping \nType' : 'Shipping Type',
    'Discount \nApplied' : 'Discount',
    'Promo Code\n Used' : 'Promo Code Used',
    'Previous\n Purchases' : 'Old Purchases',
    'Frequency of\n Purchases' : 'Frequency of Purchases',
    'Previous Purchased \nAmount (USD)' : 'Old Purchase Amount',
    'Average \nOrder Value (USD)' : 'Average Order Value (USD)', 
    'Total Sales \nRevenue Per Customer (USD)' : 'Total Sales',
    'Conversion\n Rate %' : 'Conversion Rate'
}, inplace = True)

cust_data.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount', 'Location', 'Size', 'Color', 'Season', 'Rating',
       'Subscription', 'Payment Method', 'Shipping Type', 'Discount',
       'Promo Code Used', 'Old Purchases', 'Frequency of Purchases',
       'Old Purchase Amount', 'Average Order Value (USD)', 'Total Sales',
       'Time spend on website  Minutes', ' clicks ',
       'total number of impressions', 'Click-through rate (CTR)',
       'Website Traffic', 'Conversion Rate'],
      dtype='object')

In [106]:
cust_data['Purchase Amount']=cust_data['Purchase Amount'].str.replace('$','').astype(float)
cust_data['Old Purchase Amount']=cust_data['Old Purchase Amount'].str.replace('$','').astype(float)
cust_data['Average Order Value (USD)']=cust_data['Average Order Value (USD)'].str.replace('$','').astype(float)
cust_data['Total Sales']=cust_data['Total Sales'].str.replace('$','').astype(float)
cust_data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Rating,Subscription,Payment Method,Shipping Type,Discount,Promo Code Used,Old Purchases,Frequency of Purchases,Old Purchase Amount,Average Order Value (USD),Total Sales,Time spend on website Minutes,clicks,total number of impressions,Click-through rate (CTR),Website Traffic,Conversion Rate
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Fortnightly,554.0,40.47,607.0,55,2,95,2.11%,61,3.28%
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Fortnightly,122.0,62.00,186.0,31,2,230,0.87%,41,4.88%
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Weekly,579.0,27.17,652.0,31,1,213,0.47%,106,0.94%
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,Weekly,600.0,13.80,690.0,16,0,173,0.00%,25,0.00%
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,Annually,378.0,13.34,427.0,20,1,337,0.30%,13,7.69%

In [107]:
cust_data['Click-through rate (CTR)']=cust_data['Click-through rate (CTR)'].str.replace('%','').astype(float)
cust_data['Conversion Rate']=cust_data['Conversion Rate'].str.replace('%','').astype(float)
cust_data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Rating,Subscription,Payment Method,Shipping Type,Discount,Promo Code Used,Old Purchases,Frequency of Purchases,Old Purchase Amount,Average Order Value (USD),Total Sales,Time spend on website Minutes,clicks,total number of impressions,Click-through rate (CTR),Website Traffic,Conversion Rate
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Fortnightly,554.0,40.47,607.0,55,2,95,2.11,61,3.28
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Fortnightly,122.0,62.00,186.0,31,2,230,0.87,41,4.88
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Weekly,579.0,27.17,652.0,31,1,213,0.47,106,0.94
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,Weekly,600.0,13.80,690.0,16,0,173,0.00,25,0.00
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,Annually,378.0,13.34,427.0,20,1,337,0.30,13,7.69

In [108]:
cust_data.describe()

,Customer ID,Age,Purchase Amount,Rating,Old Purchases,Old Purchase Amount,Average Order Value (USD),Total Sales,Time spend on website Minutes,clicks,total number of impressions,Click-through rate (CTR),Website Traffic,Conversion Rate
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538,305.724359,25.925403,365.488718,54.475641,0.999231,249.679744,0.424969,102.161282,1.882772
std,1125.977353,15.207589,23.685392,0.716223,14.447125,172.555121,36.930083,174.652003,26.106872,0.820517,58.263411,0.376283,56.106061,3.648740
min,1.000000,18.000000,20.000000,2.500000,1.000000,6.000000,0.820000,31.000000,10.000000,0.000000,95.000000,0.000000,5.000000,0.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000,158.000000,7.995000,216.000000,31.000000,0.000000,200.000000,0.000000,54.000000,0.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000,305.000000,13.810000,365.000000,54.000000,1.000000,250.000000,0.400000,101.000000,0.950000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000,456.000000,25.890000,516.000000,77.000000,2.000000,300.000000,0.670000,150.250000,1.920000
max,3900.000000,70.000000,100.000000,5.000000,50.000000,600.000000,336.500000,695.000000,99.000000,2.000000,350.000000,2.110000,200.000000,40.000000

how to interpret after in this cust_data.describe?

checking the duplicate values in the dataset

In [109]:

duplicates = cust_data[cust_data.duplicated()]

# To see all duplicated rows
print("Duplicate Rows:")
print(duplicates)

# To count the number of duplicates
num_duplicates = cust_data.duplicated().sum()
print(f"Number of duplicates: {num_duplicates}")

Duplicate Rows:
Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount, Location, Size, Color, Season, Rating, Subscription, Payment Method, Shipping Type, Discount, Promo Code Used, Old Purchases, Frequency of Purchases, Old Purchase Amount, Average Order Value (USD), Total Sales, Time spend on website  Minutes,  clicks , total number of impressions, Click-through rate (CTR), Website Traffic, Conversion Rate]
Index: []
Number of duplicates: 0

In [110]:
# Check data types of columns
print(cust_data.dtypes)

Customer ID                         int64
Age                                 int64
Gender                             object
Item Purchased                     object
Category                           object
Purchase Amount                   float64
Location                           object
Size                               object
Color                              object
Season                             object
Rating                            float64
Subscription                       object
Payment Method                     object
Shipping Type                      object
Discount                           object
Promo Code Used                    object
Old Purchases                       int64
Frequency of Purchases             object
Old Purchase Amount               float64
Average Order Value (USD)         float64
Total Sales                       float64
Time spend on website  Minutes      int64
 clicks                             int64
total number of impressions         int64
Click-through rate (CTR)          float64
Website Traffic                     int64
Conversion Rate                   float64
dtype: object

do we need to convert the object datatypes into string?

finding the correlation matrix or ralationship between the available columns

In [111]:
# Assuming 'cust_data' is your DataFrame
numeric_data = cust_data.select_dtypes(include='number')
categorical_data = cust_data.select_dtypes(exclude='number')

# Perform one-hot encoding or label encoding on categorical columns
# For example, using one-hot encoding:
categorical_encoded = pd.get_dummies(categorical_data)

# Concatenate numeric and encoded categorical data
combined_data = pd.concat([numeric_data, categorical_encoded], axis=1)

# Calculate correlation matrix
correlation_matrix = combined_data.corr()
print(correlation_matrix.head())

                 Customer ID       Age  Purchase Amount    Rating  \
Customer ID         1.000000 -0.004079         0.011048  0.001343
Age                -0.004079  1.000000        -0.010424 -0.021949
Purchase Amount     0.011048 -0.010424         1.000000  0.030776
Rating              0.001343 -0.021949         0.030776  1.000000
Old Purchases      -0.039159  0.040445         0.008063  0.004229

                 Old Purchases  Old Purchase Amount  \
Customer ID          -0.039159             0.022568
Age                   0.040445            -0.006716
Purchase Amount       0.008063             0.020437
Rating                0.004229            -0.008191
Old Purchases         1.000000             0.023230

                 Average Order Value (USD)  Total Sales  \
Customer ID                       0.049170     0.023795
Age                              -0.019838    -0.008049
Purchase Amount                   0.055647     0.155807
Rating                            0.016386    -0.003919
Old Purchases                    -0.595578     0.024044

                 Time spend on website  Minutes   clicks   \
Customer ID                           -0.005962  0.007355
Age                                    0.005519  0.008123
Purchase Amount                       -0.003531  0.003831
Rating                                 0.009856 -0.005346
Old Purchases                          0.009988  0.004956

                 total number of impressions  Click-through rate (CTR)  \
Customer ID                         0.002967                  0.003450
Age                                -0.014027                  0.007749
Purchase Amount                     0.000854                  0.002398
Rating                              0.014282                 -0.003840
Old Purchases                      -0.007953                  0.009495

                 Website Traffic  Conversion Rate  Gender_Female  Gender_Male  \
Customer ID            -0.012481        -0.000572       0.807960    -0.807960
Age                     0.011377         0.002137      -0.002763     0.002763
Purchase Amount        -0.012353         0.010613       0.014044    -0.014044
Rating                  0.009851        -0.005967      -0.008164     0.008164
Old Purchases          -0.030586         0.011281      -0.035873     0.035873

                 Item Purchased_Backpack  Item Purchased_Belt  \
Customer ID                    -0.021972             0.004367
Age                            -0.015055            -0.022210
Purchase Amount                 0.005167             0.000704
Rating                          0.000681             0.003344
Old Purchases                  -0.024109            -0.018255

                 Item Purchased_Blouse  Item Purchased_Boots  \
Customer ID                   0.045498             -0.005773
Age                           0.003071              0.010028
Purchase Amount               0.010063              0.023651
Rating                       -0.019832              0.017103
Old Purchases                 0.019756              0.013685

                 Item Purchased_Coat  Item Purchased_Dress  \
Customer ID                -0.028346             -0.009167
Age                        -0.011614              0.007404
Purchase Amount            -0.018888              0.021406
Rating                     -0.005654              0.001434
Old Purchases               0.021004              0.017467

                 Item Purchased_Gloves  Item Purchased_Handbag  \
Customer ID                  -0.008811                0.019067
Age                          -0.012652                0.026363
Purchase Amount               0.006401               -0.016003
Rating                        0.030808                0.007115
Old Purchases                 0.014578               -0.008940

                 Item Purchased_Hat  Item Purchased_Hoodie  \
Customer ID               -0.003916              -0.001763
Age                       -0.006887               0.010634
Purchase Amount            0.009523              -0.014447
Rating                     0.016009              -0.008616
Old Purchases             -0.000286              -0.014269

                 Item Purchased_Jacket  Item Purchased_Jeans  \
Customer ID                   0.012237             -0.024190
Age                           0.018188             -0.004084
Purchase Amount              -0.026651              0.008468
Rating                        0.003862             -0.025700
Old Purchases                -0.032224             -0.048621

                 Item Purchased_Jewelry  Item Purchased_Pants  \
Customer ID                   -0.006491             -0.017764
Age                            0.031320             -0.007965
Purchase Amount               -0.011089             -0.006859
Rating                         0.001851             -0.009340
Old Purchases                  0.052699             -0.002871

                 Item Purchased_Sandals  Item Purchased_Scarf  \
Customer ID                    0.030690              0.000456
Age                            0.001194              0.003453
Purchase Amount               -0.019776              0.009804
Rating                         0.026370             -0.014285
Old Purchases                 -0.016757              0.020301

                 Item Purchased_Shirt  Item Purchased_Shoes  \
Customer ID                  0.007389              0.000644
Age                         -0.029034              0.027072
Purchase Amount              0.012328              0.015502
Rating                      -0.035771             -0.000730
Old Purchases                0.004672             -0.001175

                 Item Purchased_Shorts  Item Purchased_Skirt  \
Customer ID                  -0.002809             -0.000015
Age                          -0.008729              0.002924
Purchase Amount               0.002754             -0.002239
Rating                       -0.011006              0.009277
Old Purchases                 0.009736             -0.007251

                 Item Purchased_Sneakers  Item Purchased_Socks  \
Customer ID                    -0.020398              0.043298
Age                            -0.018799              0.009816
Purchase Amount                -0.001764             -0.013717
Rating                          0.002190              0.000286
Old Purchases                  -0.001592             -0.005915

                 Item Purchased_Sunglasses  Item Purchased_Sweater  \
Customer ID                       0.008991               -0.028045
Age                               0.010000               -0.010101
Purchase Amount                   0.001466               -0.018306
Rating                           -0.001515                0.005010
Old Purchases                     0.003516                0.003657

                 Item Purchased_T-shirt  Category_Accessories  \
Customer ID                    0.001114             -0.003031
Age                           -0.016032              0.006993
Purchase Amount                0.026301              0.002144
Rating                         0.009132              0.017810
Old Purchases                 -0.007333              0.017690

                 Category_Clothing  Category_Footwear  Category_Outerwear  \
Customer ID               0.006718           0.003504           -0.011559
Age                      -0.016826           0.010476            0.004816
Purchase Amount           0.009875           0.008833           -0.032938
Rating                   -0.033543           0.024211           -0.001276
Old Purchases            -0.009451          -0.003524           -0.008226

                 Location_Alabama  Location_Alaska  Location_Arizona  \
Customer ID              0.000602         0.014254          0.020156
Age                      0.002474        -0.009637          0.010347
Purchase Amount         -0.004207         0.045360          0.037324
Rating                   0.006844         0.010117         -0.010199
Old Purchases            0.022194         0.026068          0.027197

                 Location_Arkansas  Location_California  Location_Colorado  \
Customer ID              -0.001199            -0.002390           0.012182
Age                       0.000310            -0.014603           0.000720
Purchase Amount           0.008194            -0.005100          -0.020523
Rating                   -0.005200             0.018708          -0.004552
Old Purchases             0.017039            -0.009372          -0.013360

                 Location_Connecticut  Location_Delaware  Location_Florida  \
Customer ID                  0.023883          -0.020709         -0.007966
Age                          0.030553          -0.009862         -0.015287
Purchase Amount             -0.033689          -0.028145         -0.022001
Rating                      -0.010987           0.009520         -0.013121
Old Purchases               -0.013366          -0.007522          0.007201

                 Location_Georgia  Location_Hawaii  Location_Idaho  \
Customer ID              0.009169        -0.022130        0.014903
Age                     -0.002802        -0.011782       -0.007888
Purchase Amount         -0.005871        -0.011222        0.002052
Rating                  -0.025279        -0.013835        0.006934
Old Purchases           -0.002743         0.034407       -0.012413

                 Location_Illinois  Location_Indiana  Location_Iowa  \
Customer ID               0.009256         -0.031819      -0.027434
Age                      -0.008033          0.037657      -0.034373
Purchase Amount           0.008467         -0.005102       0.006345
Rating                   -0.022873          0.011320       0.018342
Old Purchases             0.013410          0.004691       0.020970

                 Location_Kansas  Location_Kentucky  Location_Louisiana  \
Customer ID             0.057069          -0.000219           -0.003431
Age                    -0.008335          -0.017046            0.039871
Purchase Amount        -0.028183          -0.024546           -0.012843
Rating                  0.009524           0.000392            0.004697
Old Purchases          -0.017480           0.010613           -0.019628

                 Location_Maine  Location_Maryland  Location_Massachusetts  \
Customer ID            0.016730          -0.001103               -0.020286
Age                   -0.019912           0.027917                0.010281
Purchase Amount       -0.016644          -0.025417                0.006512
Rating                 0.018155           0.011714               -0.006640
Old Purchases         -0.026548           0.012301               -0.022194

                 Location_Michigan  Location_Minnesota  Location_Mississippi  \
Customer ID               0.019410           -0.000511             -0.002365
Age                      -0.017917            0.014077             -0.007670
Purchase Amount           0.013597           -0.020578              0.007780
Rating                    0.014144            0.000734              0.001273
Old Purchases             0.015237            0.009092              0.006622

                 Location_Missouri  Location_Montana  Location_Nebraska  \
Customer ID              -0.025513          0.014415          -0.000190
Age                       0.016017         -0.002565          -0.013925
Purchase Amount          -0.011381          0.003258          -0.002016
Rating                   -0.000617          0.012952          -0.004474
Old Purchases             0.028195         -0.000888          -0.006200

                 Location_Nevada  Location_New Hampshire  Location_New Jersey  \
Customer ID            -0.015057                0.005669             0.008409
Age                    -0.004562                0.002288             0.008359
Purchase Amount         0.023057               -0.001965            -0.016849
Rating                 -0.007869               -0.026370             0.003178
Old Purchases           0.007141                0.016469            -0.014556

                 Location_New Mexico  Location_New York  \
Customer ID                -0.004739          -0.001071
Age                        -0.000419          -0.001365
Purchase Amount             0.013141           0.004216
Rating                     -0.003630          -0.000595
Old Purchases               0.006911          -0.011609

                 Location_North Carolina  Location_North Dakota  \
Customer ID                    -0.013701              -0.010329
Age                             0.015617              -0.002884
Purchase Amount                 0.006216               0.019472
Rating                          0.012798               0.000383
Old Purchases                  -0.005759              -0.016134

                 Location_Ohio  Location_Oklahoma  Location_Oregon  \
Customer ID           0.001481          -0.010563        -0.008991
Age                   0.022997          -0.001736        -0.004705
Purchase Amount       0.003669          -0.008382        -0.014250
Rating                0.012750          -0.028277         0.002897
Old Purchases        -0.002050          -0.023054         0.001559

                 Location_Pennsylvania  Location_Rhode Island  \
Customer ID                   0.004036               0.005198
Age                          -0.010020               0.020290
Purchase Amount               0.039951               0.009090
Rating                        0.005783              -0.002405
Old Purchases                 0.019904              -0.015790

                 Location_South Carolina  Location_South Dakota  \
Customer ID                    -0.020399               0.008934
Age                             0.031815              -0.000482
Purchase Amount                -0.008075               0.004281
Rating                          0.002341              -0.013744
Old Purchases                   0.006329              -0.007034

                 Location_Tennessee  Location_Texas  Location_Utah  \
Customer ID                0.017890        0.024988       0.001996
Age                       -0.000154       -0.012397      -0.006794
Purchase Amount            0.013242        0.008572       0.016175
Rating                     0.006316        0.030766      -0.014051
Old Purchases              0.005988       -0.038031       0.017133

                 Location_Vermont  Location_Virginia  Location_Washington  \
Customer ID             -0.003673          -0.005228             0.010823
Age                     -0.014415          -0.022942             0.002986
Purchase Amount         -0.016311           0.018690             0.020787
Rating                  -0.007714          -0.008097             0.010974
Old Purchases           -0.007766          -0.018127            -0.006243

                 Location_West Virginia  Location_Wisconsin  Location_Wyoming  \
Customer ID                   -0.026417            0.004160         -0.012219
Age                           -0.014608            0.017542         -0.013983
Purchase Amount                0.025288           -0.022573          0.005323
Rating                        -0.034511            0.027776         -0.010569
Old Purchases                 -0.018107           -0.023183          0.027223

                   Size_L    Size_M    Size_S   Size_XL  Color_Beige  \
Customer ID     -0.010818  0.025022 -0.023460  0.003729    -0.018957
Age              0.020127 -0.002547 -0.006033 -0.017266     0.021687
Purchase Amount -0.030847  0.006106  0.024334  0.004848     0.005437
Rating           0.002342 -0.039267  0.027341  0.026288    -0.038808
Old Purchases    0.015026 -0.002924 -0.017913  0.004833    -0.006214

                 Color_Black  Color_Blue  Color_Brown  Color_Charcoal  \
Customer ID         0.009529    0.002424     0.011960       -0.020122
Age                 0.011292    0.011989    -0.012164        0.010642
Purchase Amount    -0.012175   -0.023898    -0.005729        0.007420
Rating              0.026632   -0.023111    -0.000274        0.009328
Old Purchases       0.006865   -0.023061     0.013829       -0.013878

                 Color_Cyan  Color_Gold  Color_Gray  Color_Green  \
Customer ID       -0.003495    0.008745    0.007155     0.009252
Age               -0.013229   -0.008438    0.012545    -0.021167
Purchase Amount    0.018939    0.010052    0.023732     0.053380
Rating            -0.036345   -0.021305    0.037584    -0.019417
Old Purchases      0.027315   -0.014461    0.042017    -0.010759

                 Color_Indigo  Color_Lavender  Color_Magenta  Color_Maroon  \
Customer ID         -0.006737       -0.001199       0.023995      0.013363
Age                 -0.010099        0.012302      -0.028005     -0.018117
Purchase Amount     -0.029355       -0.005308      -0.022388     -0.002074
Rating              -0.015872       -0.010796       0.025545      0.014543
Old Purchases       -0.012366       -0.001647      -0.015357     -0.008422

                 Color_Olive  Color_Orange  Color_Peach  Color_Pink  \
Customer ID        -0.007543     -0.004072     0.021248    0.031637
Age                -0.007625      0.014240    -0.026496   -0.001431
Purchase Amount    -0.014892      0.009634    -0.004851    0.007030
Rating             -0.007639      0.022260    -0.004188    0.014861
Old Purchases      -0.012811      0.005183     0.023855   -0.014152

                 Color_Purple  Color_Red  Color_Silver  Color_Teal  \
Customer ID         -0.014457  -0.005260     -0.005019   -0.016956
Age                 -0.005361  -0.021104      0.002716    0.014802
Purchase Amount      0.002109  -0.003747     -0.026674    0.009467
Rating               0.020151  -0.012541     -0.007549   -0.003647
Old Purchases       -0.006540   0.009659      0.014155    0.006703

                 Color_Turquoise  Color_Violet  Color_White  Color_Yellow  \
Customer ID            -0.014410      0.001715    -0.022425     -0.000254
Age                     0.013019      0.032380     0.020641     -0.005465
Purchase Amount        -0.034440      0.017383     0.023610     -0.004772
Rating                  0.013356     -0.028541     0.009954      0.034527
Old Purchases           0.007789     -0.016914     0.036493     -0.035007

                 Season_Fall  Season_Spring  Season_Summer  Season_Winter  \
Customer ID         0.020254      -0.001050      -0.012225      -0.007065
Age                 0.012277       0.019841      -0.003544      -0.028798
Purchase Amount     0.043701      -0.025439      -0.032681       0.014417
Rating             -0.016124       0.033304      -0.019318       0.001739
Old Purchases      -0.015239      -0.009564       0.002241       0.022686

                 Subscription_No  Subscription_Yes  \
Customer ID             0.768960         -0.768960
Age                    -0.006492          0.006492
Purchase Amount         0.006996         -0.006996
Rating                  0.006368         -0.006368
Old Purchases          -0.030859          0.030859

                 Payment Method_Bank Transfer  Payment Method_Cash  \
Customer ID                          0.003587            -0.009963
Age                                 -0.009073             0.012850
Purchase Amount                     -0.019041             0.003074
Rating                               0.015772            -0.004104
Old Purchases                        0.024751            -0.009003

                 Payment Method_Credit Card  Payment Method_Debit Card  \
Customer ID                       -0.000666                  -0.013000
Age                                0.012611                  -0.024573
Purchase Amount                    0.027457                  -0.020931
Rating                            -0.007167                  -0.016233
Old Purchases                     -0.031045                  -0.005080

                 Payment Method_PayPal  Payment Method_Venmo  \
Customer ID                   0.016335              0.003730
Age                          -0.015439              0.022776

In [112]:
unique_values =cust_data['Gender'].value_counts()
print(unique_values)

Gender
Male      2652
Female    1248
Name: count, dtype: int64

In [119]:
cust_data.loc[cust_data.Gender=='Male'].head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Rating,Subscription,Payment Method,Shipping Type,Discount,Promo Code Used,Old Purchases,Frequency of Purchases,Old Purchase Amount,Average Order Value (USD),Total Sales,Time spend on website Minutes,clicks,total number of impressions,Click-through rate (CTR),Website Traffic,Conversion Rate
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Fortnightly,554.0,40.47,607.0,55,2,95,2.11,61,3.28
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Fortnightly,122.0,62.00,186.0,31,2,230,0.87,41,4.88
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Weekly,579.0,27.17,652.0,31,1,213,0.47,106,0.94
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,Weekly,600.0,13.80,690.0,16,0,173,0.00,25,0.00
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,Annually,378.0,13.34,427.0,20,1,337,0.30,13,7.69

In [114]:
cust_data.loc[cust_data.Gender=='Female'].head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Rating,Subscription,Payment Method,Shipping Type,Discount,Promo Code Used,Old Purchases,Frequency of Purchases,Old Purchase Amount,Average Order Value (USD),Total Sales,Time spend on website Minutes,clicks,total number of impressions,Click-through rate (CTR),Website Traffic,Conversion Rate
2652,2653,23,Female,Shorts,Clothing,20.0,Maryland,L,Cyan,Summer,3.3,No,Debit Card,2-Day Shipping,No,No,46,Monthly,325.0,7.34,345.0,29,2,195,1.03,113,1.77
2653,2654,67,Female,Blouse,Clothing,36.0,Wisconsin,L,Lavender,Fall,4.8,No,Credit Card,Express,No,No,24,Every 3 Months,580.0,24.64,616.0,95,1,165,0.61,51,1.96
2654,2655,23,Female,Coat,Outerwear,70.0,Idaho,S,Pink,Fall,4.1,No,Debit Card,Next Day Air,No,No,4,Annually,449.0,103.80,519.0,66,2,343,0.58,164,1.22
2655,2656,26,Female,Sunglasses,Accessories,83.0,Wyoming,M,Gray,Summer,3.4,No,Credit Card,Standard,No,No,2,Fortnightly,15.0,32.67,98.0,27,0,307,0.00,176,0.00
2656,2657,52,Female,Shorts,Clothing,76.0,Indiana,L,Yellow,Winter,3.6,No,Bank Transfer,Express,No,No,29,Fortnightly,210.0,9.53,286.0,78,1,308,0.32,28,3.57

In [115]:
unique_item =cust_data['Item Purchased'].value_counts()
print(unique_item)

Item Purchased
Blouse        171
Jewelry       171
Pants         171
Shirt         169
Dress         166
Sweater       164
Jacket        163
Belt          161
Sunglasses    161
Coat          161
Sandals       160
Socks         159
Skirt         158
Shorts        157
Scarf         157
Hat           154
Handbag       153
Hoodie        151
Shoes         150
T-shirt       147
Sneakers      145
Boots         144
Backpack      143
Gloves        140
Jeans         124
Name: count, dtype: int64

In [116]:
cust_data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Rating,Subscription,Payment Method,Shipping Type,Discount,Promo Code Used,Old Purchases,Frequency of Purchases,Old Purchase Amount,Average Order Value (USD),Total Sales,Time spend on website Minutes,clicks,total number of impressions,Click-through rate (CTR),Website Traffic,Conversion Rate
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Fortnightly,554.0,40.47,607.0,55,2,95,2.11,61,3.28
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Fortnightly,122.0,62.00,186.0,31,2,230,0.87,41,4.88
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Weekly,579.0,27.17,652.0,31,1,213,0.47,106,0.94
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,Weekly,600.0,13.80,690.0,16,0,173,0.00,25,0.00
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,Annually,378.0,13.34,427.0,20,1,337,0.30,13,7.69

checking outliers

In [117]:
from sklearn.ensemble import IsolationForest

# Initialize Isolation Forest model
model = IsolationForest(contamination=0.05)  # Adjust contamination parameter
model.fit(cust_data)

# Predict outliers
outliers = model.predict(cust_data) == -1
print("Rows identified as outliers:")
print(cust_data[outliers])

ValueError: could not convert string to float: 'Male'